name: Build Website (Production)

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Build static website
      working-directory: ./services/pool-website
      run: |
        npm install
        npm run build
        npm run export
        git config --global user.name "${{ secrets.CI_USERNAME }}"
        git config --global user.email "${{ secrets.CI_EMAIL }}"
        PAT64=$(echo ":${{ secrets.PERSONAL_ACCESS_TOKEN }}" | base64)
        git -c http.extraHeader="Authorization: Basic $PAT64" clone https://${{ secrets.CI_USERNAME }}:${{ secrets.CI_PASSWORD }}@github.com/wcatz/wcatz.github.io.git /tmp/repo
        rm -rf /tmp/repo/_next
        cp -R out/* /tmp/repo
    - name: Push changes to GitHub Pages repo
      working-directory: /tmp/repo
      run: |
        pwd
        git add --all 
        git commit -m 'update build' 
        git config --global user.name "${{ secrets.CI_USERNAME }}"
        git config --global user.email "${{ secrets.CI_EMAIL }}"
        git remote set-url origin https://${{ secrets.CI_USERNAME }}:${{ secrets.CI_PASSWORD }}@github.com/wcatz/wcatz.github.io.git
        git push origin master